language: java
jdk: oraclejdk7
branches:
  only:
    - master
before_install:
  #  - chmod +x gradlew
  # Install base Android SDK
  - sudo apt-get update -qq
  #- if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - export URL_ANDROID_SDK="http://dl.google.com/android/android-sdk_r22.3-linux.tgz"
  - export FILENAME_SDK="android-sdk_r22.3-linux.tgz"
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Go!
  - wget -q $URL_ANDROID_SDK
  - tar xzf $FILENAME_SDK
  - echo yes | android -s update sdk --filter platform-tools --no-ui > /dev/null
  - echo yes | android -s update sdk --filter android-19 --no-ui > /dev/null
  - echo yes | android -s update sdk -a --filter "build-tools-19.0.1" --no-ui > /dev/null
  
before_script:
  - android -s update project --path . --name "Pingr" --target "android-19"
  
script:
  - ant clean
  - ant debug